INSERT INTO inventory_schema.inventory
    (product_id, quantity, reserved_quantity, created_at, updated_at)
VALUES
    (501, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (502, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (503, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (601, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (701, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (801, 100, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
