spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/omnichannel_test
    username: app_user
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    schemas: payment_schema
    default-schema: payment_schema