package com.diluwar.order.service;

import com.diluwar.order.client.InventoryClient;
import com.diluwar.order.client.PaymentClient;
import com.diluwar.order.dto.CreateOrderRequest;
import com.diluwar.order.dto.OrderItemRequest;
import com.diluwar.order.dto.OrderResponse;
import com.diluwar.order.entity.Order;
import com.diluwar.order.entity.OrderStatus;
import com.diluwar.order.repository.OrderRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestClient;

@ExtendWith(MockitoExtension.class)
class OrderServiceTest {

    @Mock
    private OrderRepository orderRepository;

    private OrderService orderService;

    @Mock
    private InventoryClient inventoryClient;

    @Mock
    private PaymentClient paymentClient;

    @BeforeEach
    void setUp() {
        orderService = new OrderService(
        orderRepository,
        inventoryClient,
        paymentClient
  );
    }

    @BeforeEach
    void setupInventory() {

    RestClient inventoryClient = RestClient.builder()
            .baseUrl("http://localhost:8083")
            .build();

    createInventory(inventoryClient, 501L, 100);
    createInventory(inventoryClient, 502L, 100);
    createInventory(inventoryClient, 503L, 100);
    createInventory(inventoryClient, 601L, 100);
    createInventory(inventoryClient, 602L, 100);
    createInventory(inventoryClient, 701L, 100);
}

private void createInventory(
        RestClient client,
        Long productId,
        int quantity) {

    try {
        client.post()
                .uri("/api/v1/inventory")
                .contentType(MediaType.APPLICATION_JSON)
                .body("""
                        {
                            "productId": %d,
                            "quantity": %d
                        }
                        """.formatted(productId, quantity))
                .retrieve()
                .toBodilessEntity();
    } catch (Exception ignored) {
        // Inventory may already exist from another test run.
    }
}

    @Test
    void shouldCreateOrderWithCalculatedTotal() {

        CreateOrderRequest request = new CreateOrderRequest(
                1001L,
                List.of(
                        new OrderItemRequest(101L, 2, new BigDecimal("50.00")),
                        new OrderItemRequest(102L, 3, new BigDecimal("25.00"))
                )
        );

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(1L);

                    order.getItems().forEach(item -> {
                        if (item.getId() == null) {
                            // IDs are generated by the database in production.
                            // No need to assign them for this unit test.
                        }
                    });

                    return order;
                });

        OrderResponse response = orderService.createOrder(request);

        assertNotNull(response);
        assertEquals(1L, response.id());
        assertEquals(1001L, response.customerId());
        assertEquals(OrderStatus.CREATED, response.status());

        // 2 * 50 + 3 * 25 = 175
        assertEquals(
        new BigDecimal("175.00"),
        response.totalAmount()
);

        assertEquals(2, response.items().size());

        verify(orderRepository, times(1)).save(any(Order.class));
    }

    @Test
    void shouldCreateOrderWithSingleItem() {

        CreateOrderRequest request = new CreateOrderRequest(
                2001L,
                List.of(
                        new OrderItemRequest(501L, 4, new BigDecimal("20.00"))
                )
        );

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(10L);
                    return order;
                });

        OrderResponse response = orderService.createOrder(request);

        assertEquals(10L, response.id());
        assertEquals(2001L, response.customerId());
        assertEquals(OrderStatus.CREATED, response.status());
        assertEquals(
        new BigDecimal("80.00"),
        response.totalAmount()
);
        assertEquals(1, response.items().size());

        verify(orderRepository).save(any(Order.class));
    }

    @Test
    void shouldBuildOrderWithCorrectCustomerAndItems() {

        CreateOrderRequest request = new CreateOrderRequest(
                3001L,
                List.of(
                        new OrderItemRequest(701L, 2, new BigDecimal("100.00")),
                        new OrderItemRequest(702L, 1, new BigDecimal("75.50"))
                )
        );

        ArgumentCaptor<Order> orderCaptor =
                ArgumentCaptor.forClass(Order.class);

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(20L);
                    return order;
                });

        orderService.createOrder(request);

        verify(orderRepository).save(orderCaptor.capture());

        Order savedOrder = orderCaptor.getValue();

        assertEquals(3001L, savedOrder.getCustomerId());
        assertEquals(OrderStatus.CREATED, savedOrder.getStatus());
        assertEquals(
        new BigDecimal("275.50"),
        savedOrder.getTotalAmount()
);

        assertNotNull(savedOrder.getCreatedAt());
        assertNotNull(savedOrder.getUpdatedAt());

        assertEquals(2, savedOrder.getItems().size());

        assertEquals(701L, savedOrder.getItems().get(0).getProductId());
        assertEquals(2, savedOrder.getItems().get(0).getQuantity());
        assertEquals(
        new BigDecimal("100.00"),
        savedOrder.getItems().get(0).getUnitPrice()
);

        assertEquals(702L, savedOrder.getItems().get(1).getProductId());
        assertEquals(1, savedOrder.getItems().get(1).getQuantity());
        assertEquals(
        new BigDecimal("75.50"),
        savedOrder.getItems().get(1).getUnitPrice()
);
    }

    @Test
    void shouldCalculateTotalForMultipleItems() {

        CreateOrderRequest request = new CreateOrderRequest(
                4001L,
                List.of(
                        new OrderItemRequest(1L, 2, new BigDecimal("10.50")),
                        new OrderItemRequest(2L, 5, new BigDecimal("7.25")),
                        new OrderItemRequest(3L, 1, new BigDecimal("100.00"))
                )
        );

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(30L);
                    return order;
                });

        OrderResponse response = orderService.createOrder(request);

        // 21.00 + 36.25 + 100.00 = 157.25
        assertEquals(
        new BigDecimal("157.25"),
        response.totalAmount()
);

        verify(orderRepository).save(any(Order.class));
    }

    @Test
    void shouldSetOrderStatusToCreated() {

        CreateOrderRequest request = new CreateOrderRequest(
                5001L,
                List.of(
                        new OrderItemRequest(901L, 1, new BigDecimal("50.00"))
                )
        );

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(40L);
                    return order;
                });

        OrderResponse response = orderService.createOrder(request);

        assertEquals(OrderStatus.CREATED, response.status());
    }

    @Test
    void shouldSetCreatedAndUpdatedTimestamp() {

        CreateOrderRequest request = new CreateOrderRequest(
                6001L,
                List.of(
                        new OrderItemRequest(1001L, 1, new BigDecimal("100.00"))
                )
        );

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(50L);
                    return order;
                });

        OrderResponse response = orderService.createOrder(request);

        assertNotNull(response.createdAt());
        assertNotNull(response.updatedAt());

        assertEquals(
                response.createdAt(),
                response.updatedAt()
        );
    }

    @Test
    void shouldCreateCorrectOrderItemRelationship() {

        CreateOrderRequest request = new CreateOrderRequest(
                7001L,
                List.of(
                        new OrderItemRequest(1101L, 2, new BigDecimal("15.00"))
                )
        );

        ArgumentCaptor<Order> orderCaptor =
                ArgumentCaptor.forClass(Order.class);

        when(orderRepository.save(any(Order.class)))
                .thenAnswer(invocation -> {
                    Order order = invocation.getArgument(0);
                    order.setId(60L);
                    return order;
                });

        orderService.createOrder(request);

        verify(orderRepository).save(orderCaptor.capture());

        Order savedOrder = orderCaptor.getValue();

        assertEquals(1, savedOrder.getItems().size());

        assertSame(
                savedOrder,
                savedOrder.getItems().get(0).getOrder()
        );
    }

    @Test
void shouldGetOrderById() {

    Order order = new Order();

    order.setId(100L);
    order.setCustomerId(8001L);
    order.setStatus(OrderStatus.CREATED);
    order.setTotalAmount(new BigDecimal("250.00"));

    Instant now = Instant.now();

    order.setCreatedAt(now);
    order.setUpdatedAt(now);

    when(orderRepository.findById(100L))
            .thenReturn(java.util.Optional.of(order));

    OrderResponse response = orderService.getOrder(100L);

    assertNotNull(response);
    assertEquals(100L, response.id());
    assertEquals(8001L, response.customerId());
    assertEquals(OrderStatus.CREATED, response.status());
    assertEquals(
            new BigDecimal("250.00"),
            response.totalAmount()
    );

    assertNotNull(response.createdAt());
    assertNotNull(response.updatedAt());

    assertEquals(0, response.items().size());

    verify(orderRepository).findById(100L);
}

    @Test
    void shouldThrowOrderNotFoundExceptionWhenOrderDoesNotExist() {

    when(orderRepository.findById(999L))
            .thenReturn(java.util.Optional.empty());

    OrderNotFoundException exception =
            assertThrows(
                    OrderNotFoundException.class,
                    () -> orderService.getOrder(999L)
            );

    assertEquals(
            "Order not found: 999",
            exception.getMessage()
    );

    verify(orderRepository).findById(999L);
    }

    @Test
void shouldGetOrders() {

    Order order = new Order();

    order.setId(200L);
    order.setCustomerId(9001L);
    order.setStatus(OrderStatus.CREATED);
    order.setTotalAmount(new BigDecimal("300.00"));

    Instant now = Instant.now();

    order.setCreatedAt(now);
    order.setUpdatedAt(now);

    Pageable pageable = PageRequest.of(0, 10);

    Page<Order> orderPage =
            new PageImpl<>(
                    List.of(order),
                    pageable,
                    1
            );

    when(orderRepository.findAll(pageable))
            .thenReturn(orderPage);

    Page<OrderResponse> response =
            orderService.getOrders(pageable);

    assertNotNull(response);
    assertEquals(1, response.getTotalElements());
    assertEquals(1, response.getContent().size());

    OrderResponse orderResponse =
            response.getContent().get(0);

    assertEquals(200L, orderResponse.id());
    assertEquals(9001L, orderResponse.customerId());
    assertEquals(OrderStatus.CREATED, orderResponse.status());
    assertEquals(
            new BigDecimal("300.00"),
            orderResponse.totalAmount()
    );

    verify(orderRepository).findAll(pageable);
}

@Test
void shouldReturnEmptyPageWhenNoOrdersExist() {

    Pageable pageable = PageRequest.of(0, 10);

    Page<Order> emptyPage =
            new PageImpl<>(
                    List.of(),
                    pageable,
                    0
            );

    when(orderRepository.findAll(pageable))
            .thenReturn(emptyPage);

    Page<OrderResponse> response =
            orderService.getOrders(pageable);

    assertNotNull(response);
    assertTrue(response.isEmpty());
    assertEquals(0, response.getTotalElements());
    assertEquals(0, response.getContent().size());

    verify(orderRepository).findAll(pageable);
}

@Test
void shouldUpdateOrderStatus() {

    Order order = new Order();

    order.setId(300L);
    order.setCustomerId(10001L);
    order.setStatus(OrderStatus.CREATED);
    order.setTotalAmount(new BigDecimal("500.00"));

    Instant createdAt = Instant.now();
    Instant updatedAt = createdAt;

    order.setCreatedAt(createdAt);
    order.setUpdatedAt(updatedAt);

    when(orderRepository.findById(300L))
            .thenReturn(java.util.Optional.of(order));

    when(orderRepository.save(order))
            .thenReturn(order);

    OrderResponse response =
            orderService.updateStatus(
                    300L,
                    OrderStatus.CONFIRMED
            );

    assertNotNull(response);
    assertEquals(300L, response.id());
    assertEquals(OrderStatus.CONFIRMED, response.status());
    assertEquals(
            new BigDecimal("500.00"),
            response.totalAmount()
    );

    assertNotNull(response.updatedAt());
    assertTrue(
            response.updatedAt().compareTo(updatedAt) >= 0
    );

    verify(orderRepository).findById(300L);
    verify(orderRepository).save(order);
}

@Test
void shouldThrowOrderNotFoundExceptionWhenUpdatingMissingOrder() {

    when(orderRepository.findById(999L))
            .thenReturn(java.util.Optional.empty());

    OrderNotFoundException exception =
            assertThrows(
                    OrderNotFoundException.class,
                    () -> orderService.updateStatus(
                            999L,
                            OrderStatus.CONFIRMED
                    )
            );

    assertEquals(
            "Order not found: 999",
            exception.getMessage()
    );

    verify(orderRepository).findById(999L);
    verify(orderRepository, never()).save(any(Order.class));
}

@Test
void shouldDeleteOrder() {

    Order order = new Order();

    order.setId(400L);
    order.setCustomerId(11001L);
    order.setStatus(OrderStatus.CREATED);
    order.setTotalAmount(new BigDecimal("150.00"));

    Instant now = Instant.now();

    order.setCreatedAt(now);
    order.setUpdatedAt(now);

    when(orderRepository.findById(400L))
            .thenReturn(java.util.Optional.of(order));

    orderService.deleteOrder(400L);

    verify(orderRepository).findById(400L);
    verify(orderRepository).delete(order);
}

@Test
void shouldThrowOrderNotFoundExceptionWhenDeletingMissingOrder() {

    when(orderRepository.findById(999L))
            .thenReturn(java.util.Optional.empty());

    assertThrows(
            OrderNotFoundException.class,
            () -> orderService.deleteOrder(999L)
    );

    verify(orderRepository).findById(999L);
    verify(orderRepository, never()).delete(any(Order.class));
}

}